# netlify.toml
[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = "dist"
  
# Handle SPA routing - this is crucial for the app to work correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Environment variables for the frontend
[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"